[package]
name = "stage1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_reqs = { path = "../../shared/core_reqs" }

[profile.release]
opt-level = "s"
lto = true

